packing/urls.py
from django.contrib.auth.decorators import login_required
from . import views
from django.urls import path


urlpatterns = [
    # Home is set to search_plans to avoid any errors linked to plan status.
    path("", login_required(views.search_plans), name="home"),

    # _______________SEARCH VIEWS_______________
    path(
        "search/products", login_required(views.search_products), name="search-products"
    ),
    path(
        "search/plans",
        login_required(views.search_plans),
        name="search-plans"),
    path(
        "search/packaging",
        login_required(views.search_packaging),
        name="search-packaging",
    ),
    path(
        "search/runs",
        login_required(views.search_runs),
        name="search-runs"
    ),
    # _______________DETAIL_______________
    path(
        "plan/<int:pk>/detail",
        views.login_required(views.DetailPlanView.as_view()),
        name="plan-detail",
    ),
    # Live plan custom detail view
    path(
        "plan/live-plan",
        login_required(views.live_plan),
        name="live-plan",
    ),
    # _______________CREATE_______________
    # plan create
    path(
        "plan/create/",
        login_required(views.CreatePlanView.as_view()),
        name="plan-create",
    ),
    # product create
    path(
        "product/create/",
        login_required(views.CreateProductView.as_view()),
        name="product-create",
    ),
    # packaging create
    path(
        "packaging/create/",
        login_required(views.CreatePackagingView.as_view()),
        name="packaging-create",
    ),
    # run create
    path(
        "run/create/",
        login_required(views.CreateRunView.as_view()),
        name="run-create"
    ),
    # packing-run create
    path(
        "packing-run/create/<int:pk>",
        login_required(views.CreatePackingView.as_view()),
        name="packing-run-create",
    ),
    # live-packing-run create
    path(
        "live-packing-run/create/<int:pk>",
        views.login_required(views.CreateLivePackingView.as_view()),
        name="live-packing-run-create",
    ),
    # _______________UPDATE_______________
    # plan update
    path(
        "plan/<int:pk>/update/",
        login_required(views.UpdatePlanView.as_view()),
        name="plan-update",
    ),
    # product update
    path(
        "product/<int:pk>/update/",
        views.login_required(views.UpdateProductView.as_view()),
        name="product-update",
    ),
    # packaging update
    path(
        "packaging/<int:pk>/update/",
        login_required(views.UpdatePackagingView.as_view()),
        name="packaging-update",
    ),
    # run update
    path(
        "run/<int:pk>/update/",
        login_required(views.UpdateRunView.as_view()),
        name="run-update",
    ),
    # packing-run update
    path(
        "packing-run/<int:pk>/update/",
        login_required(views.UpdatePackingView.as_view()),
        name="packing-run-update",
    ),
    # live-packing-run update
    path(
        "live-packing-run/<int:pk>/update/",
        login_required(views.UpdateLivePackingView.as_view()),
        name="live-packing-run-update",
    ),
    # _______________DELETE_______________
    # plan delete
    path(
        "plan/<int:pk>/delete/",
        login_required(views.DeletePlanView.as_view()),
        name="plan-delete",
    ),
    # product delete
    path(
        "product/<int:pk>/delete/",
        login_required(views.DeleteProductView.as_view()),
        name="product-delete",
    ),
    # packaging delete
    path(
        "packaging/<int:pk>/delete/",
        login_required(views.DeletePackagingView.as_view()),
        name="packaging-delete",
    ),
    # run delete
    path(
        "run/<int:pk>/delete/",
        login_required(views.DeleteRunView.as_view()),
        name="run-delete",
    ),
    # packing-run delete
    path(
        "packing-run/<int:pk>/delete/",
        login_required(views.DeletePackingView.as_view()),
        name="packing-run-delete",
    ),
    # live-packing-run delete
    path(
        "live-packing-run/<int:pk>/delete/",
        login_required(views.DeleteLivePackingView.as_view()),
        name="live-packing-run-delete",
    ),
]

planner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('packing.urls'), name='packing_urls'),
    path('accounts/', include('allauth.urls')),
]

handler404='packing.views.handle_404'
handler403='packing.views.handle_403'
handler500='packing.views.handle_500'

packing/models.py
from django.db import models, transaction
from django.contrib.auth.models import User
from django.db.models import F, Sum, Q
from .managers import PackingRunManager


PLANNING_STATUS = (
    (0, "Planning"),
    (1, "Current"),
    (2, "Complete"),
    (3, "Delete")
)
DAYS = (
    (1, "Saturday"),
    (2, "Monday"),
    (3, "Tuesday"),
    (4, "Wednesday"),
    (5, "Thursday"),
    (6, "Friday"),
)
COMPLETE = (("No", "NO"), ("Yes", "YES"))


class Pack(models.Model):
    """
    Model representing a particular combination of packaging
    that can be assigned to a product.
    """

    name = models.CharField(
        max_length=50,
        unique=True,
        help_text="Name of the packing configuration."
    )
    film = models.CharField(
        max_length=50,
        help_text="Film used to seal an inner pack.")
    inner = models.CharField(max_length=50, help_text="The inner packet.")
    srp = models.CharField(
        max_length=50, default="No SRP", help_text="Shelf Ready Pack."
    )
    outer = models.CharField(
        max_length=50,
        help_text="The outer box or case in which inners are packed."
    )

    def __str__(self):
        return self.name


class Team(models.Model):
    """
    Model representing a packing team.
    """

    name = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    Model representing a finished product
    which can be assigned to a run.
    """

    name = models.CharField(max_length=50)
    customer = models.CharField(max_length=50)
    packaging = models.ForeignKey(
        Pack,
        on_delete=models.CASCADE,
        help_text="Name of the packing configuration."
    )
    ppt = models.FloatField(help_text="Portions Per Tray.")
    pack_sz = models.IntegerField(help_text="Portions Per Pack.")
    ppc = models.FloatField(help_text="Portions Per Case")

    def __str__(self):
        return self.customer + " " + self.name


class Week(models.Model):
    """
    Model representing a week plan.
    """

    name = models.CharField(
        max_length=50,
        unique=True,
        help_text="such as: October 2022 Wk2, for the second week of october.",
    )
    start_date = models.DateField(
        auto_now=False,
        auto_now_add=False,
        help_text="Date the plan begins,Enter as YYYY-MM-DD.",
    )
    status = models.IntegerField(
        choices=PLANNING_STATUS,
        help_text="Set Status. Select 'Delete' for Admin to action.",
    )

    class Meta:
        ordering = ["-start_date"]

    def get_absolute_url(self):
        return reverse("plan-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name


class Run(models.Model):
    """
    Model representing a run of a particular product
    which can be assigned to a week plan.
    """

    name = models.CharField(
        max_length=50,
        unique=True,
        help_text="Customer, Name & cases e.g. 'Charducks Trillionaire 230'",
    )
    case_qty = models.IntegerField(
        help_text="The number of cases that need to be packed to meet orders."
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        help_text="Select a Product to add to this Run.",
    )

    def __str__(self):
        return self.name


class PackingRun(models.Model):
    """
    Model representing Runs that have been assigned to a
    particular week plan.
    """

    name = models.ForeignKey(
        Run, on_delete=models.CASCADE, help_text="Click Field To See Choices"
    )
    week = models.ForeignKey(
        Week,
        on_delete=models.CASCADE,
        help_text="Automatically Chooses Correct Plan Week",
    )
    team = models.ForeignKey(
        Team, on_delete=models.CASCADE, help_text="Click Field To See Choices"
    )
    day = models.IntegerField(
        choices=DAYS,
        help_text="Click Field To See Choices"
    )
    time = models.IntegerField(
        help_text="Estimated time in minutes to complete the packing-run."
    )
    notes = models.TextField(blank=True, null=True, help_text="Optional")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_when = models.DateTimeField(auto_now=True)
    complete = models.CharField(max_length=50, choices=COMPLETE, default="No")

    # Custom model manager
    objects = PackingRunManager()

    class Meta:
        ordering = ["day"]

    def __str__(self):
        return self.week.name + " " + self.name.name

templates/detail/live-plan-detail.html
{% extends 'detail/plan-detail.html'%}
<!--
  Exactly the same format as the plan-detail but displays in a different view for the "Current" Plan
  when the "Live Packing Calculator" nav link is clicked. 
-->

<!--Change the CREATE view so that on completion redirects to live-plan-->
{% block create-template %}href="{% url 'live-packing-run-create' week.id %}"{% endblock create-template %}

<!--Change the UPDATE view so that on completion redirects to live-plan-->
{% block update-template %}href="{% url 'live-packing-run-update' run.id %}"{% endblock update-template %}

<!--Change the DELETE view so that on completion redirects to live-plan-->
{% block delete-template %}href="{% url 'live-packing-run-delete' run.id %}"{% endblock delete-template %}

templates/detail/plan-detail.html
{% extends '../partials/base.html'%}

<!--Tab Title-->
{% block title %}Plan Detail | {{ week.name }}{% endblock title %}

<!--Content displaying plan info and buttons-->
{% block content %}
<div class="container">
  <!--Change colour of the status badges depending on selected status-->
  {% if week.get_status_display == 'Current' %}
    <div class="card text-white bg-info">
  {% elif week.get_status_display == 'Planning' %}
    <div class="card text-white bg-warning">
  {% else %}
    <div class="card text-white bg-dark">
  {% endif %}
    <!--Header with plan info-->
    <div class="card-header text-center">
      <h2>
        <br>
        {{ week.name }} |
        {{ week.start_date | date:"d M Y" }} |
        {{ week.get_status_display }}
      </h2>
      <br>
      <!--Plan action buttons-->
      <div class="d-flex align-items-center justify-content-center">
        <!--Add run button does not display if the week status is set to Complete-->
        {% if week.status != 2 %}
          <!--Button only displays if user has appropriate editing permission-->
          {% if perms.packing.create_week %}
            <a class="btn btn-primary btn-lg" {% block create-template %}href="{% url 'packing-run-create' week.id %}"{% endblock create-template %}><i
                class="fa-regular fa-square-plus"></i>&nbsp;Add Run to Plan
            </a>&nbsp;&nbsp;
          {% endif %}
        {% endif %}
        <!--Button that opens the notes modal-->
        <button class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#note-modal">
          <i class="fa-solid fa-comment"></i>&nbsp;Notes
        </button>&nbsp;&nbsp;
      </div>
      <br>
    </div>
  </div>
</div>
<br>
{% endblock content %}

<!--Accordion containing report tables for the plan-->
{% block accordion %}
<div class="container accordion-container">
  <div class="accordion" id="detail-accordion">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <!--Accordion No.1 collapse toggle-->
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne"
          aria-expanded="true" aria-controls="collapseOne">
          <!--Accordion No.1 title-->
          <h4>Plan Summary</h4>
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne">
        <div class="accordion-body">
          <!--Accordion No.1 table content -->
          <div class="table-container">
            <table class="table table-striped text-center table-responsive-sm">
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Cases Required</th>
                  <th>Team</th>
                  <th>Day</th>
                  <th>Created</th>
                  <th>Created By</th>
                  <th>Completed</th>
                </tr>
              </thead>
              <tbody>
                <!--Accordion No.1 Data loop-->
                {% for run in runs %}
                  {% if run.complete == 'Yes' %}
                    <tr class="table-success">
                  {% else %}
                    <tr class="table-light">
                  {% endif %}
                      <td>{{ run.name.product }}</td>
                      <td>{{ run.name.case_qty }}</td>
                      <td>{{ run.team }}</td>
                      <td>{{ run.get_day_display }}</td>
                      <td>{{ run.created_when }}</td>
                      <td>{{ run.created_by }}</td>
                      <td><strong>{{ run.get_complete_display }}</strong></td>
                      <td>
                        {% if perms.packing.edit_packingrun %}
                        <a class="btn btn-outline-primary" {% block update-template %}href="{% url 'packing-run-update' run.id %}"{% endblock update-template %}><i
                            class="fa-solid fa-pen-to-square"></i></a>
                        {% endif %}
                        {% if perms.packing.delete_packingrun %}
                        <a class="btn btn-outline-danger" {% block delete-template %}href="{% url 'packing-run-delete' run.id %}"{% endblock delete-template %}><i
                            class="fa-regular fa-trash-can"></i></a>
                        {% endif %}
                      </td>
                    </tr>
                {% empty %}
                    <div class="row justify-content-md-center">Currently no data available to be displayed, add runs to plan to populate tables.</div>
                    <br>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <!--Accordion No.2 collapse toggle-->
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo"
          aria-expanded="true" aria-controls="collapseTwo">
          <!--Accordion No.2 title-->
          <h4>Plan Calculations</h4>
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse show" aria-labelledby="headingTwo">
        <div class="accordion-body">
          <!--Accordion No.2 table content -->
          <div class="table-container">
            <table class=" table table-striped text-center">
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Cases Required</th>
                  <th>Day</th>
                  <th>Est Packets</th>
                  <th>Portions/Tray</th>
                  <th>Portions/Case</th>
                  <th>Calculated Trays</th>
                </tr>
              </thead>
              <tbody>
                <!--Accordion No.2 Data loop-->
                {% for run in runs %}
                  <tr>
                    <td>{{ run.name.product }}</td>
                    <td>{{ run.name.case_qty }}</td>
                    <td>{{ run.get_day_display }}</td>
                    <td>{{ run.est_packets | floatformat:"0g" }}</td>
                    <td>{{ run.name.product.ppt | floatformat:"0g"  }}</td>
                    <td>{{ run.name.product.ppc | floatformat:"0g"}}</td>
                    <td>{{ run.trays | floatformat:"0g" }}</td>
                    <td>
                      {% if perms.packing.edit_packingrun %}
                      <a class="btn btn-outline-primary" href="{% url 'packing-run-update' run.id %}">
                        <i class="fa-solid fa-pen-to-square"></i>
                      </a>
                      {% endif %}
                    </td>
                  </tr>
                {% empty %}
                <div class="row justify-content-md-center">Currently no data available to be displayed, add runs to plan to populate tables.</div>
                  <br>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <!--Accordion No.3 collapse toggle-->
        <button class="accordion-button" type="button" data-bs-toggle="collapse"
          data-bs-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
          <!--Accordion No.3 title-->
          <h4>Team Times (minutes)</h4>
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse show" aria-labelledby="headingThree">
        <div class="accordion-body">
          <!--Accordion No.3 table content -->
          <div class="table-container">
            <table class=" table table-striped text-center">
              <thead>
                <tr>
                  <th>Team</th>
                  <th>Saturday</th>
                  <th>Monday</th>
                  <th>Tuesday</th>
                  <th>Wednesday</th>
                  <th>Thurday</th>
                  <th>Friday</th>
                  <th>Total</th>
                </tr>
              </thead>
              <tbody>
                <!--The lists tdt and tt are in order of team/day
                and can therefore be gone through in order-->
                <tr>
                  <td>Team 1</td>
                  <td>{{ tdt.0 }}</td>
                  <td>{{ tdt.1 }}</td>
                  <td>{{ tdt.2 }}</td>
                  <td>{{ tdt.3 }}</td>
                  <td>{{ tdt.4 }}</td>
                  <td>{{ tdt.5 }}</td>
                  <td>{{ tt.0 }}</td>
                </tr>
                <tr>
                  <td>Team 2</td>
                  <td>{{ tdt.6 }}</td>
                  <td>{{ tdt.7 }}</td>
                  <td>{{ tdt.8 }}</td>
                  <td>{{ tdt.9 }}</td>
                  <td>{{ tdt.10 }}</td>
                  <td>{{ tdt.11 }}</td>
                  <td>{{ tt.1 }}</td>
                </tr>
                <tr>
                  <td>Team 3</td>
                  <td>{{ tdt.12 }}</td>
                  <td>{{ tdt.13 }}</td>
                  <td>{{ tdt.14 }}</td>
                  <td>{{ tdt.15 }}</td>
                  <td>{{ tdt.16 }}</td>
                  <td>{{ tdt.17 }}</td>
                  <td>{{ tt.2 }}</td>
                </tr>
                <tr>
                  <td>Twilight</td>
                  <td>{{ tdt.18 }}</td>
                  <td>{{ tdt.19 }}</td>
                  <td>{{ tdt.20 }}</td>
                  <td>{{ tdt.21 }}</td>
                  <td>{{ tdt.22 }}</td>
                  <td>{{ tdt.23 }}</td>
                  <td>{{ tt.3 }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingFour">
        <!--Accordion No.4 collapse toggle-->
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour"
          aria-expanded="true" aria-controls="collapseFour">
          <!--Accordion No.4 title-->
          <h4>Packaging Required</h4>
        </button>
      </h2>
      <div id="collapseFour" class="accordion-collapse collapse show" aria-labelledby="headingFour">
        <div class="accordion-body">
          <!--Accordion No.4 table content -->
          <div class="table-container">
            <table class="table table-striped packaging-table">
              <thead>
                <tr>
                  <th>Film ROLLS</th>
                  <th>Required</th>
                  <th>Day</th>
                </tr>
              </thead>
              <tbody class="text-center">
                <!--Accordion No.4 Data loop-->
                {% for run in runs %}
                  <tr>
                    <td>{{ run.name.product.packaging.film }}</td>
                    <td>{{ run.film_rolls|floatformat:"0g" }}</td>
                    <td>{{ run.get_day_display }}</td>
                  </tr>
                {% empty %}
                <div class="row justify-content-md-center">Currently no data available to be displayed, add runs to plan to populate tables.</div>
                  <br>
                {% endfor %}
              </tbody>
            </table>
            <table class="table table-striped packaging-table">
              <thead>
                <tr>
                  <th>Inner Packets</th>
                  <th>Required</th>
                  <th>Day</th>
                </tr>
              </thead>
              <tbody>
                {% for run in runs %}
                  <tr>
                    <td>{{ run.name.product.packaging.inner }}</td>
                    <td>{{ run.est_packets|floatformat:"0g"}}</td>
                    <td>{{ run.get_day_display }}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
            <table class="table table-striped packaging-table">
              <thead>
                <tr>
                  <th>Outer Cases</th>
                  <th>Required</th>
                  <th>Day</th>
                </tr>
              </thead>
              <tbody>
                {% for run in runs %}
                  <tr>
                    <td>{{ run.name.product.packaging.outer }}</td>
                    <td>{{ run.name.case_qty|floatformat:"0g" }}</td>
                    <td>{{ run.get_day_display }}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br><br><br>
{% endblock accordion %}