packing/urls.py
from django.contrib.auth.decorators import login_required
from . import views
from django.urls import path


urlpatterns = [
    # Home is set to search_plans to avoid any errors linked to plan status.
    path("", login_required(views.search_plans), name="home"),

    # _______________SEARCH VIEWS_______________
    path(
        "search/products", login_required(views.search_products), name="search-products"
    ),
    path(
        "search/plans",
        login_required(views.search_plans),
        name="search-plans"),
    path(
        "search/packaging",
        login_required(views.search_packaging),
        name="search-packaging",
    ),
    path(
        "search/runs",
        login_required(views.search_runs),
        name="search-runs"
    ),
    # _______________DETAIL_______________
    path(
        "plan/<int:pk>/detail",
        views.login_required(views.DetailPlanView.as_view()),
        name="plan-detail",
    ),
    # Live plan custom detail view
    path(
        "plan/live-plan",
        login_required(views.live_plan),
        name="live-plan",
    ),
    # _______________CREATE_______________
    # plan create
    path(
        "plan/create/",
        login_required(views.CreatePlanView.as_view()),
        name="plan-create",
    ),
    # product create
    path(
        "product/create/",
        login_required(views.CreateProductView.as_view()),
        name="product-create",
    ),
    # packaging create
    path(
        "packaging/create/",
        login_required(views.CreatePackagingView.as_view()),
        name="packaging-create",
    ),
    # run create
    path(
        "run/create/",
        login_required(views.CreateRunView.as_view()),
        name="run-create"
    ),
    # packing-run create
    path(
        "packing-run/create/<int:pk>",
        login_required(views.CreatePackingView.as_view()),
        name="packing-run-create",
    ),
    # live-packing-run create
    path(
        "live-packing-run/create/<int:pk>",
        views.login_required(views.CreateLivePackingView.as_view()),
        name="live-packing-run-create",
    ),
    # _______________UPDATE_______________
    # plan update
    path(
        "plan/<int:pk>/update/",
        login_required(views.UpdatePlanView.as_view()),
        name="plan-update",
    ),
    # product update
    path(
        "product/<int:pk>/update/",
        views.login_required(views.UpdateProductView.as_view()),
        name="product-update",
    ),
    # packaging update
    path(
        "packaging/<int:pk>/update/",
        login_required(views.UpdatePackagingView.as_view()),
        name="packaging-update",
    ),
    # run update
    path(
        "run/<int:pk>/update/",
        login_required(views.UpdateRunView.as_view()),
        name="run-update",
    ),
    # packing-run update
    path(
        "packing-run/<int:pk>/update/",
        login_required(views.UpdatePackingView.as_view()),
        name="packing-run-update",
    ),
    # live-packing-run update
    path(
        "live-packing-run/<int:pk>/update/",
        login_required(views.UpdateLivePackingView.as_view()),
        name="live-packing-run-update",
    ),
    # _______________DELETE_______________
    # plan delete
    path(
        "plan/<int:pk>/delete/",
        login_required(views.DeletePlanView.as_view()),
        name="plan-delete",
    ),
    # product delete
    path(
        "product/<int:pk>/delete/",
        login_required(views.DeleteProductView.as_view()),
        name="product-delete",
    ),
    # packaging delete
    path(
        "packaging/<int:pk>/delete/",
        login_required(views.DeletePackagingView.as_view()),
        name="packaging-delete",
    ),
    # run delete
    path(
        "run/<int:pk>/delete/",
        login_required(views.DeleteRunView.as_view()),
        name="run-delete",
    ),
    # packing-run delete
    path(
        "packing-run/<int:pk>/delete/",
        login_required(views.DeletePackingView.as_view()),
        name="packing-run-delete",
    ),
    # live-packing-run delete
    path(
        "live-packing-run/<int:pk>/delete/",
        login_required(views.DeleteLivePackingView.as_view()),
        name="live-packing-run-delete",
    ),
]

planner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('packing.urls'), name='packing_urls'),
    path('accounts/', include('allauth.urls')),
]

handler404='packing.views.handle_404'
handler403='packing.views.handle_403'
handler500='packing.views.handle_500'

packing/models.py
from django.db import models, transaction
from django.contrib.auth.models import User
from django.db.models import F, Sum, Q
from .managers import PackingRunManager


PLANNING_STATUS = (
    (0, "Planning"),
    (1, "Current"),
    (2, "Complete"),
    (3, "Delete")
)
DAYS = (
    (1, "Saturday"),
    (2, "Monday"),
    (3, "Tuesday"),
    (4, "Wednesday"),
    (5, "Thursday"),
    (6, "Friday"),
)
COMPLETE = (("No", "NO"), ("Yes", "YES"))


class Pack(models.Model):
    """
    Model representing a particular combination of packaging
    that can be assigned to a product.
    """

    name = models.CharField(
        max_length=50,
        unique=True,
        help_text="Name of the packing configuration."
    )
    film = models.CharField(
        max_length=50,
        help_text="Film used to seal an inner pack.")
    inner = models.CharField(max_length=50, help_text="The inner packet.")
    srp = models.CharField(
        max_length=50, default="No SRP", help_text="Shelf Ready Pack."
    )
    outer = models.CharField(
        max_length=50,
        help_text="The outer box or case in which inners are packed."
    )

    def __str__(self):
        return self.name


class Team(models.Model):
    """
    Model representing a packing team.
    """

    name = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    Model representing a finished product
    which can be assigned to a run.
    """

    name = models.CharField(max_length=50)
    customer = models.CharField(max_length=50)
    packaging = models.ForeignKey(
        Pack,
        on_delete=models.CASCADE,
        help_text="Name of the packing configuration."
    )
    ppt = models.FloatField(help_text="Portions Per Tray.")
    pack_sz = models.IntegerField(help_text="Portions Per Pack.")
    ppc = models.FloatField(help_text="Portions Per Case")

    def __str__(self):
        return self.customer + " " + self.name


class Week(models.Model):
    """
    Model representing a week plan.
    """

    name = models.CharField(
        max_length=50,
        unique=True,
        help_text="such as: October 2022 Wk2, for the second week of october.",
    )
    start_date = models.DateField(
        auto_now=False,
        auto_now_add=False,
        help_text="Date the plan begins,Enter as YYYY-MM-DD.",
    )
    status = models.IntegerField(
        choices=PLANNING_STATUS,
        help_text="Set Status. Select 'Delete' for Admin to action.",
    )

    class Meta:
        ordering = ["-start_date"]

    def get_absolute_url(self):
        return reverse("plan-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name


class Run(models.Model):
    """
    Model representing a run of a particular product
    which can be assigned to a week plan.
    """

    name = models.CharField(
        max_length=50,
        unique=True,
        help_text="Customer, Name & cases e.g. 'Charducks Trillionaire 230'",
    )
    case_qty = models.IntegerField(
        help_text="The number of cases that need to be packed to meet orders."
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        help_text="Select a Product to add to this Run.",
    )

    def __str__(self):
        return self.name


class PackingRun(models.Model):
    """
    Model representing Runs that have been assigned to a
    particular week plan.
    """

    name = models.ForeignKey(
        Run, on_delete=models.CASCADE, help_text="Click Field To See Choices"
    )
    week = models.ForeignKey(
        Week,
        on_delete=models.CASCADE,
        help_text="Automatically Chooses Correct Plan Week",
    )
    team = models.ForeignKey(
        Team, on_delete=models.CASCADE, help_text="Click Field To See Choices"
    )
    day = models.IntegerField(
        choices=DAYS,
        help_text="Click Field To See Choices"
    )
    time = models.IntegerField(
        help_text="Estimated time in minutes to complete the packing-run."
    )
    notes = models.TextField(blank=True, null=True, help_text="Optional")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_when = models.DateTimeField(auto_now=True)
    complete = models.CharField(max_length=50, choices=COMPLETE, default="No")

    # Custom model manager
    objects = PackingRunManager()

    class Meta:
        ordering = ["day"]

    def __str__(self):
        return self.week.name + " " + self.name.name

templates/search/search-packaging.html
{% extends 'search/search-index.html' %}

<!--Tab title-->
{% block title %}Search | Packaging Configs{% endblock title %}

<!--Active page class insert-->
{% block packaging-style %}active{% endblock packaging-style %}

<!--Template specific content-->
{% block search-packaging %}
<br><br>

<!--Search bar section-->
<div class="container border-0">
    <div class="card border-0">
        <form class="d-flex">
            {% csrf_token %}
            <input class="form-control me-2" type="search" placeholder="Search for a packing config..."
                aria-label="search" name="search-query">
            <button class="btn btn-primary" type="submit">Search</button>&nbsp;
            <button class="btn btn-secondary">Clear</button>
        </form>
    </div>
</div>
<br><br>

<!--Container holding all item cards-->
<div class="container text-center">
    <div class="card">
        <div class="card-header">
            <!--Create packing config button displaying for users with appropriate permissions-->
            {% if perms.packing.create_packaging %}
                <a class="btn btn-success mx-auto" href="{% url 'packaging-create' %}"> Create New Packaging Config </a>
            {% else %}
            <!--If user does not have permission they see this title instead of button-->
                <h5 class="text-center">Browse all existing Packing Configurations below or search for specific above...</h5>
            {% endif %}
        </div>
        <div class="card-body">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                <!--Data loop-->
                {% for pack in queryset %}
                    <!--Cards generated for each record existing in the database-->
                    <div class="col">
                        <br>
                        <div class="card">
                            <div class="card-header">
                                <h5 class="mx-auto">{{ pack.name }}</h5>
                            </div>
                            <div class="card-body">
                                <p><span class="badge text-bg-warning">Film</span> | <strong>{{ pack.film }}</strong></p>
                                <p><span class="badge text-bg-warning">Inner</span> | <strong>{{ pack.inner }}</strong></p>
                                <p><span class="badge text-bg-warning">SRP</span> | <strong>{{ pack.srp }}</strong></p>
                                <p><span class="badge text-bg-warning">Outer</span> | <strong>{{ pack.outer }}</strong></p>
                            </div>
                            <div class="card-footer">
                                <!--Edit and delete buttons, only displayed if user has appropriate permission-->
                                {% if perms.packing.edit_packaging %}
                                    <!--Edit button-->
                                    <a class="btn btn-outline-primary" href="{% url 'packaging-update' pack.id%}"><i
                                        class="fa-solid fa-pen-to-square"></i>&nbsp;Edit</a>
                                {% endif %}
                                {% if perms.packing.delete_pack %}
                                    <!--Delete button-->
                                    <a class="btn btn-outline-danger" href="{% url 'packaging-delete' pack.id %}"><i
                                        class="fa-regular fa-trash-can"></i></a>
                                {% endif %}
                            </div>
                        </div>
                        <br>
                    </div>
                {% empty %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <p>Your Search came back empty ... Try searching for a term in the item title</p>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
                <br>
            </div>
        </div>
    </div>
</div>
<br><br><br>
{% endblock search-packaging %}

templates/search/search-plans.html
{% extends 'search/search-index.html' %}

<!--Tab title-->
{% block title %}Search | Week Plans{% endblock title %}

<!--Active page class insert-->
{% block plan-style %}active{% endblock plan-style %}

<!--Template specific content-->
{% block search-plan %}
<br><br>
<!--Search bar section-->
<div class="container border-0">
    <div class="card border-0">
        <form class="d-flex">
            {% csrf_token %}
            <input class="form-control me-2" type="search" placeholder="Search for week plan..." aria-label="search"
                name="search-query">
            <button class="btn btn-primary" type="submit">Search</button>&nbsp;
            <button class="btn btn-secondary">Clear</button>
        </form>
    </div>
</div>
<br><br>
<!-- Warning Alert - only one plan can be set to current -->
{% if perms.packing.edit_week %}
<div class="container text-center">
    <div class="alert alert-secondary alert-dismissible fade show" role="alert">
        <h5>
            <i class="fa-solid fa-triangle-exclamation"></i>&nbsp;
            Only one plan can be set to 'Current' status at any given time.
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <br>
        <button class="btn btn-outline-info" type="button" data-bs-toggle="collapse" data-bs-target="#collapseHelp" aria-expanded="false" aria-controls="collapseHelp">
            More Info
        </button>
        <br>
        <div class="collapse alert alert-secondary border-0" id="collapseHelp">
            <div class="card card-body alert alert-secondary border-0" style="width: 50%; margin: auto;">
               <h6>
                    For the 'Live Plan' nav-link to work there MUST be a plan with status set to 
                    'Current' but ONLY ONE.&nbsp;None or more than one will cause an error.
               </h6>
               <br>
               <div>
                    <strong>How To Change Plan Status</strong>
                    <ol class="plan-alert-list">
                        <li>Find existing 'Current' Plan</li>
                        <li>Click the 'Edit' Button</li>
                        <li>Change the status to 'Complete' and click 'Update'.</li>
                        <li>Follow the same steps for the desired new 'Current' plan, setting status to 'Current'</li>
                        <li><strong><u>If you have no plan set to 'Current' the 'Live Plan' link will not work.</u></strong></li>
                    </ol>
                    <button class="btn btn-outline-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseHelp" aria-expanded="false" aria-controls="collapseHelp">
                        Less Info
                    </button>
               </div>
            </div>
        </div>
    </div>
</div>
{% endif %}

<!--Container holding all item cards-->
<div class="container text-center">
    <div class="card">
        <div class="card-header">
            <!--Create plan button displaying for users with appropriate permissions-->
            {% if perms.packing.create_week %}
                <a class="btn btn-success mx-auto" href="{% url 'plan-create' %}"> Create New Plan </a>
            {% else %}
                <!--If user does not have permission they see this title instead of button-->
                <h5 class="text-center">Browse existing plans below or search for specific above...</h5>
            {% endif %}
        </div>
        <div class="card-body">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                <!--Data loop-->
                {% for week in queryset %}
                    <!--Cards generated for each record existing in the database-->
                    <div class="col plan-card">
                        <br>
                        <!--Card border colours change depending on the status of the plan-->
                        {% if week.get_status_display == 'Current' %}
                            <div class="card border-primary">
                        {% elif week.get_status_display == 'Planning' %}
                            <div class="card border-warning">
                        {% elif week.get_status_display == 'Delete' %}
                            <div class="card border-danger">
                        {% else %}
                            <div class="card border-dark">
                        {% endif %}
                            <div class="card-header">
                                <h5 class="mx-auto"><strong>{{ week.name }}</strong></h5>
                            </div>
                            <!--Card body colours change depending on the status of the plan-->
                            {% if week.get_status_display == 'Current' %}
                                <div class="card-body border-primary">
                            {% elif week.get_status_display == 'Planning' %}
                                <div class="card-body border-warning">
                            {% elif week.get_status_display == 'Delete' %}
                                <div class="card-body border-danger">
                            {% else %}
                                <div class="card-body outline-dark">
                            {% endif %}
                                    {% if week.get_status_display == 'Delete' %}
                                        <p><span class="badge text-bg-danger">Inactive: To Be Deleted.</span></p>
                                    {% else %}
                                        <p><span class="badge text-bg-light">Week Start Date</span> | <span
                                                class="badge text-bg-dark">{{ week.start_date | date:"d M Y" }}</span></p>
                                    {% endif %}
                                    <!--Badge colours change depending on status of the plan-->
                                    {% if week.get_status_display == 'Current' %}
                                        <p><span class="badge text-bg-primary">Status</span> | <span
                                            class="badge text-bg-primary">{{ week.get_status_display }}</span></p>
                                    {% elif week.get_status_display == 'Planning' %}
                                        <p><span class="badge text-bg-warning">Status</span> | <span
                                            class="badge text-bg-warning">{{ week.get_status_display }}</span></p>
                                    {% elif week.get_status_display == 'Delete' %}
                                        <p><span class="badge text-bg-danger">Status</span> | <span
                                            class="badge text-bg-danger">{{ week.get_status_display }}</span></p>
                                    {% else %}
                                        <p><span class="badge text-bg-secondary">Status</span> | <span
                                            class="badge text-bg-secondary">{{ week.get_status_display }}</span></p>
                                    {% endif %}
                            </div>
                            <div class="card-footer">
                                <!--View plan button visible to all users-->
                                {% if week.get_status_display != 'Delete' %}
                                    <a class="btn btn-outline-success" href="{% url 'plan-detail' week.id %}"><i
                                        class="fa-solid fa-eye"></i>&nbsp;View</a>
                                {% endif %}
                                <!--Edit plan button visibile only to users with appropriate permission-->
                                {% if perms.packing.edit_week %}
                                    <a class="btn btn-outline-primary" href="{% url 'plan-update' week.id %}"><i
                                        class="fa-solid fa-pen-to-square"></i>&nbsp;Edit</a>
                                {% endif %}
                                {% if perms.packing.delete_week %}
                                    <!--Delete button-->
                                    <a class="btn btn-outline-danger" href="{% url 'plan-delete' week.id %}"><i
                                        class="fa-regular fa-trash-can"></i></a>
                                {% endif %}
                            </div>
                        </div>
                        <br>
                    </div>
                {% empty %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <p>Your Search came back empty ... Try searching for a term in the item title</p>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
                <br>
            </div>
        </div>
    </div>
</div>
<br><br><br>
{% endblock search-plan %}

templates/search/search-products.html
{% extends 'search/search-index.html' %}

<!--Tab title-->
{% block title %}Search | Products{% endblock title %}

<!--Active page class insert-->
{% block product-style %}active{% endblock product-style %}

<!--Template specific content-->
{% block search-products %}
<br><br>

<!--Search bar section-->
<div class="container border-0">
    <div class="card border-0">
        <form class="d-flex">
            {% csrf_token %}
            <input class="form-control me-2" type="search" placeholder="Search for a product..." aria-label="search"
                name="search-query">
            <button class="btn btn-primary" type="submit">Search</button>&nbsp;
            <button class="btn btn-secondary">Clear</button>
        </form>
    </div>
</div>
<br><br>

<!--Container holding all item cards-->
<div class="container text-center">
    <div class="card">
        <div class="card-header">
            <!--Create product button displaying for users with appropriate permissions-->
            {% if perms.packing.create_product %}
                <a class="btn btn-success mx-auto" href="{% url 'product-create' %}"> Create New Product </a>
            {% else %}
                <!--If user does not have permission they see this title instead of button-->
                <h5 class="text-center">Browse existing products below or search for specific above...</h5>
            {% endif %}
        </div>
        <div class="card-body">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                <!--Data loop-->
                {% for product in queryset %}
                    <!--Cards generated for each record existing in the database-->
                    <div class="col">
                        <br>
                        <div class="card">
                            <div class="card-header">
                                <h5 class="mx-auto"><strong>{{ product }}</strong></h5>
                            </div>
                            <div class="card-body">
                                <p><span class="badge text-bg-success">Customer</span> |
                                    <strong>{{ product.customer }}</strong></p>
                                <p><span class="badge text-bg-success">Packaging Config</span> |
                                    <strong>{{ product.packaging }}</strong></p>
                                <p><span class="badge text-bg-success">Portions/Tray</span> |
                                    <strong>{{ product.ppt }}</strong></p>
                                <p><span class="badge text-bg-success">Pack Size</span> |
                                    <strong>{{ product.pack_sz }}</strong></p>
                                <p><span class="badge text-bg-success">Portions/Case</span> |
                                    <strong>{{ product.ppc }}</strong></p>
                            </div>
                            <div class="card-footer">
                                <!--Edit and delete buttons, only displayed if user has appropriate permission-->
                                {% if perms.packing.edit_product %}
                                    <!--Edit button-->
                                    <a class="btn btn-outline-primary" href="{% url 'product-update' product.id %}"><i
                                        class="fa-solid fa-pen-to-square"></i>&nbsp;Edit</a>
                                {% endif %}
                                {% if perms.packing.delete_product %}
                                    <!--Delete button-->
                                    <a class="btn btn-outline-danger" href="{% url 'product-delete' product.id %}"><i
                                        class="fa-regular fa-trash-can"></i></a>
                                {% endif %}
                            </div>
                        </div>
                        <br>
                    </div>
                {% empty %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <p>Your Search came back empty ... Try searching for a term in the item title</p>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
                <br>
            </div>
        </div>
    </div>
</div>
<br><br><br>
{% endblock search-products %}

templates/search/search-runs.html
{% extends 'search/search-index.html' %}

<!--Tab title-->
{% block title %}Search | Runs{% endblock title %}

<!--Active page class insert-->
{% block run-style %}active{% endblock run-style %}

<!--Template specific content-->
{% block search-runs %}
<br><br>

<!--Search bar section-->
<div class="container border-0">
    <div class="card border-0">
        <form class="d-flex">
            {% csrf_token %}
            <input class="form-control me-2" type="search" placeholder="Search for a run..." aria-label="search"
                name="search-query">
            <button class="btn btn-primary" type="submit">Search</button>&nbsp;
            <button class="btn btn-secondary">Clear</button>
        </form>
    </div>
</div>
<br><br>

<!--Container holding all item cards-->
<div class="container text-center">
    <div class="card">
        <div class="card-header">
            <!--Create run button displaying for users with appropriate permissions-->
            {% if perms.packing.create_run %}
                <a class="btn btn-success mx-auto" href="{% url 'run-create' %}"> Create New Run </a>
            {% else %}
                <!--If user does not have permission they see this title instead of button-->
                <h5 class="text-center">Browse existing runs below or search for specific above...</h5>
            {% endif %}
        </div>
        <div class="card-body">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                <!--Data loop-->
                {% for run in queryset %}
                    <!--Cards generated for each record existing in the database-->
                    <div class="col">
                        <br>
                        <div class="card">
                            <div class="card-header">
                                <h5 class="mx-auto">{{ run }}</h5>
                            </div>
                            <div class="card-body">
                                <p><span class="badge text-bg-danger">Product</span> | <strong>{{ run.product }}</strong></p>
                                <p><span class="badge text-bg-danger">Cases</span> | <strong>{{ run.case_qty }}</strong></p>
                            </div>
                            <div class="card-footer">
                                <!--Edit and delete buttons, only displayed if user has appropriate permission-->
                                {% if perms.packing.edit_run %}
                                <!--Edit button-->
                                    <a class="btn btn-outline-primary" href="{% url 'run-update' run.id %}"><i
                                        class="fa-solid fa-pen-to-square"></i>&nbsp;Edit</a>
                                {% endif %}      
                                {% if perms.packing.delete_run %}
                                <!--Delete button-->
                                    <a class="btn btn-outline-danger" href="{% url 'run-delete' run.id %}"><i
                                        class="fa-regular fa-trash-can"></i></a>
                                {% endif %}
                            </div>
                        </div>
                        <br>
                    </div>
                {% empty %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <p>Your Search came back empty ... Try searching for a term in the item title</p>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
                <br>
            </div>
        </div>
    </div>
</div>
<br><br><br>
{% endblock search-runs %}